esphome:
  name: ansluta-control-light
  comment: Ansluta Controller as dimmable light

  includes:
    - ansluta/cc2500_REG.h
    - ansluta/cc2500_VAL.h
    - ansluta/cc2500_CMD.h
    - ansluta/ansluta-control.h
    - ansluta/ansluta-control-light.h
  libraries:
    - SPI

esp8266:
  board: nodemcuv2

# Enable logging    
logger:

# Enable Home Assistant API
api:

ota:
  password: "aad6a56a1b6bd7192a6d53bca80f2f53"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ansluta-Light Fallback Hotspot"
    password: "c0yRTrQM0aGm"

captive_portal:

light:
- platform: custom
  lambda: |-
    auto light_out = new AnslutaControlLight();
    App.register_component(light_out);
    return {light_out};

  lights:
    - name: "Ansluta Light"
      default_transition_length: 0s